Add virtualized list that comes with RN 0.65
ifsnow/react-native-infinite-flatlist-patch pull request #7
Opened 2021-08-20 12:03 UTC by rpavlovs

Closes: #6 

@andyrobert3 could you please test it?

2021-08-20 21:45 UTC, andyrobert3 commented
@rpavlovs i think we forgot to update the `patch.js` file here

2021-08-20 22:27 UTC, andyrobert3 requested changes

2021-08-20 22:27 UTC, andyrobert3 commented on patches/0.65.0/VirtualizedList.js
> +    if (distanceFromEnd  visibleLength * 1.5) {
`distanceFromEnd >= visibleLength * 1.5`

2021-08-20 22:27 UTC, andyrobert3 commented on patches/0.65.0/VirtualizedList.js
> +    if (distanceFromEnd  minimumDistanceFromEnd) {
`distanceFromEnd >= minimumDistanceFromEnd`

2021-08-22 02:45 UTC, ifsnow commented
@rpavlovs Thanks for your PR!

There were many changes in RN 0.65. So, It's necessary to make sure that this fix does not have any issues.

Please wait for a while to check this.

2021-08-22 04:16 UTC, ifsnow commented
@rpavlovs @andyrobert3  A new version with support for RN 0.65.x has been released. Hope it works well.

2021-08-22 04:16 UTC, closed without merging